[package]
name = "yashiki-layout-tatami"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
yashiki-ipc.path = "../yashiki-ipc"
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
